// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NBDGreenerGrass.Data;

#nullable disable

namespace NBDGreenerGrass.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240127082256_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");
#pragma warning restore 612, 618
        }
    }
}
